### ISSUE TITLE
Is there a way to train with Voxceleb 1 Dataset?

### ISSUE THREAD

**Issue by psh01087** [grey-eye/talking-heads#10]
In paper, they trained the model with VoxCeleb 1 Dataset for comparison with other models. Is there any code to train with VoxCeleb 1 Dataset?? Or do you plan to implement the code?? VoxCeleb 2 Dataset is too large, so I would like to experiment with VoxCeleb1...

**Comment by MrCaracara** [comment]
VoxCeleb1 is more difficult to download as it only provides with the coordinates and timestamps of every video, but it should be exactly the same in regard to the format, so you can also use it if you manage to download it.

If you just want a smaller dataset, you can simply use a subset of VoxCeleb2.
