### ISSUE TITLE
Question about M networks

### ISSUE THREAD

**Issue by jinSloth** [grey-eye/talking-heads#12]
I think it must be very easy and simple issue, 

but i'm beginner and i can only Guess but not know exact answer. 

so, i wonder that in your cool repo,

Why isn't there saving network  M??
it's because it don't care about M but network E can embed with M? 

So that is the cause why there is only saving process about E?

in repo,
   NETWORK ----------------------------------------------------------------------------------------------------------

    E = network.Embedder().type(dtype)
    M = network.MappingNetwork(8,512).type(dtype)
    G = network.Generator().type(dtype)
    D = network.Discriminator(143000).type(dtype)

    if continue_id is not None:
        E = load_model(E, continue_id)
        M = load_model(M, continue_id)
        G = load_model(G, continue_id)
        D = load_model(D, continue_id)

There is loading preocess about M

BUT 

    # SAVE MODELS --------------------------------------------------------------------------------------------------

        save_model(E, device, run_start)
        save_model(G, device, run_start)
        save_model(D, device, run_start)
        epoch_end = datetime.now()

THERE ISN'T Saving preocess about M 

so i just wonder 

thank you

**Comment by MrCaracara** [comment]
Hi @jinSloth.

This code snippet is not from the original repo. Are you showing me a piece of code from someone's fork?
