### ISSUE TITLE
face_alignment module

### ISSUE THREAD

**Issue by IMJONEZZ** [grey-eye/talking-heads#17]
In dataset.py there's a command, "from face_alignment import FaceAlignment, LandmarksType" Where can I access that? Currently there's no face_alignment.py in this repo, and I'm having trouble trying to access it as a module.

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-6cb7b5f71ee3> in <module>
     23 import PIL
     24 import numpy as np
---> 25 from face_alignment import FaceAlignment, LandmarksType
     26 from torch.utils.data import Dataset
     27 

ModuleNotFoundError: No module named 'face_alignment'

**Comment by MrCaracara** [comment]
Have you executed the requirements.txt file? it seems like you're missing the face-alignment pip dependency.

**Comment by IMJONEZZ** [comment]
I definitely have. I'm getting an error that pip cannot find a face-alignment module.

**Comment by Cortlandd** [comment]
> 
> 
> I definitely have. I'm getting an error that pip cannot find a face-alignment module.

https://pypi.org/project/face-alignment/
