### ISSUE TITLE
About the result

### ISSUE THREAD

**Issue by ZHUTAO142857** [grey-eye/talking-heads#19]
Hello, I am also trying to build a network to synthesis talking head. This is my result. But I am now stagnant. So can we have a talk about about this paper?
![ep19_sp1000_img](https://user-images.githubusercontent.com/31002842/61046422-a61e9e80-a40f-11e9-8ec3-f03ce2cf35b4.png)

**Comment by MrCaracara** [comment]
Hi @ZHUTAO142857, I haven't had much time in the last couple of weeks to improve the model, let's talk when I have made some more progress.

**Comment by davidtranno1** [comment]
Hi @ZHUTAO142857 , did you use feature matching term in your implementation? I found that it is not so important.
