### ISSUE TITLE
About AdaptiveResidualBlock

### ISSUE THREAD

**Issue by yujitong** [grey-eye/talking-heads#27]
In the implementation of AdaptiveResidualBlock, 

    def forward(self, x, mean1, std1, mean2, std2):
        residual = x

        out = self.conv1(x)
        out = self.in1(out, mean1, std1)
        out = F.relu(out)
        out = self.conv2(out)
        out = self.in2(out, mean1, std1)

Should it be self.in2(out, mean2, std2) instead?

**Comment by castelo-software** [comment]
Yep. You're right.
