### ISSUE TITLE
Use bilinear interpolation? 

### ISSUE THREAD

**Issue by Connor323** [grey-eye/talking-heads#30]
Thanks a lot for the great efforts! I asked the same question in a different implementation [here](https://github.com/vincent-thevenin/Realistic-Neural-Talking-Head-Models/issues/15)

Although the Samsung paper didn't mention the interpolation method, according to the style-gan paper, they actually used bilinear interpolation for up/downsampling operations. When I train using your code, I have seen the checkerboard effect a lot especially in the early training stage. Have you considered using the bilinear interpolation method for the upsampling function?

**Comment by Connor323** [comment]
By the way, Augustus also mentioned this checkerboard issue and solution [here](https://distill.pub/2016/deconv-checkerboard/#citation)

**Comment by castelo-software** [comment]
Hi @Connor323,
Thanks for your suggestion. I have seen your results with this technique in the other implementation. I think the checkerboard (or ringing) effect would become less noticeable after fine-tuning. However, I haven't gotten the fine-tuning working yet so I can't test it.

If I get time to continue working on this project at some point, I'll check it out.

**Comment by Connor323** [comment]
Thanks!!
