### ISSUE TITLE
Creating output for a custom face

### ISSUE THREAD

**Issue by sleebapaul** [grey-eye/talking-heads#34]
Hi,

It could be a completely stupid question, but can I generate the video of the moving face for a custom image? All I'm left with is an image, not any other dataset related to it. Or it is specific to only the VoxCeleb2 dataset?

**Comment by castelo-software** [comment]
@sleebapaul, I haven't gotten around to making the fine-tuning phase work yet. You would need fine tuning to generate good quality frames for your custom image. Of course, this model only generates images. Once fine-tuning works, you'll still need to generate all frames and then combine them into a video.
