### ISSUE TITLE
Could you tell us about with model we should download cuz I got key error when loading VGGFace 16.

### ISSUE THREAD

**Issue by keishatsai** [grey-eye/talking-heads#5]
Hi I just try to run the meta-learning part, but encounter the following error.
Could you tell me which part was wrong?
I am using VGGFace 16 at this moment. Did I download the wrong file or should I change which part of code?
Thank you.
-------------
`  File "run.py", line 283, in <module>
    main()
  File "run.py", line 279, in main
    raise e
  File "run.py", line 265, in main
    continue_id=args.continue_id,
  File "run.py", line 67, in meta_train
    criterion_E_G = network.LossEG(device, feed_forward=True)
  File "D:\talking-heads\network\loss.py", line 17, in __init__
    self.VGG_FACE_AC = VGG_Activations(vgg_face(pretrained=True), [1, 6, 11, 18, 25]).type(self.dtype)
  File "D:\talking-heads\network\vgg.py", line 36, in vgg_face
    model.load_state_dict(vgg_face_state_dict())
  File "D:\talking-heads\network\vgg.py", line 43, in vgg_face_state_dict
    'features.0.weight': default['conv1_1.weight'],
KeyError: 'conv1_1.weight'`

**Comment by akshay951228** [comment]
i also getting same error , can you tell me how to solve this error
