### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by keishatsai** [grey-eye/talking-heads#6]
Hi, 
I was trying to train, but I couldn't manage it successfully. I am wondering what type of GPU and the size of memory you are using?

Tried few times with just 5 to 10 videos, but still not working. The error message always say the memory is not enough.
My GPU is 1080Ti with memory 8G.

or could you tell me which part of code I should adjust before I start training?
Thank you.

`Starting training loop. Epochs: 100 Dataset Size: 4
Something went wrong: CUDA out of memory. Tried to allocate 280.00 MiB (GPU 0; 8.00 GiB total capacity; 5.69 GiB already allocated; 172.65 MiB free; 354.74 MiB cached)
Traceback (most recent call last):
  File "run.py", line 281, in <module>
    main()
  File "run.py", line 277, in main
    raise e
  File "run.py", line 263, in main
    continue_id=args.continue_id,
  File "run.py", line 119, in meta_train
    loss_D.backward()
  File "C:\talking-heads\lib\site-packages\torch\tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\talking-heads\lib\site-packages\torch\autograd\__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 280.00 MiB (GPU 0; 8.00 GiB total capacity; 5.69 GiB already allocated; 172.65 MiB free; 354.74 MiB cached)`

**Comment by MrCaracara** [comment]
I find it a bit strange that 5.69GB of your GPU's memory are already allocated by the time you start training. Are you sure nothing else is running on your computer that might be using your GPU? I also see that you're running it on Windows. I have had many problems I could never explain when using PyTorch/Tensorflow ok Windows, whereas with Linux it usually works more smoothly right out of the box.

Even if you only have 8GB, it should be enough to start training. But you can also try to use half precision float tensors to speed it up a bit. 

I can tell you though, that it will take very long to train on that GPU. I have been trying on one V100 and it would take around 20 days to do as many epochs as the authors did.

**Comment by keishatsai** [comment]
Thank you for the help.
Sorry for the late reply. I was out of town in the past days.
Yes, I ran the program on Windows. It seems that Windows somehow will hold part of memory.....and I eventually got around 6GB memory could use. I have already cleaned up some background programs, run by Windows, but still get this error message. Finally, I have to narrow down the channels from 512 to 256, so I could start running the training stage.
Now, epoch 27, but the loss of D is pretty high...."2", is it normal?

**Comment by MrCaracara** [comment]
If either the loss of D of E gets stuck on a high or low value, your network has gotten stuck. I haven't let the network train for so long yet, and I'm still working on improving a lot of things. I can't say what is going wrong, but you'll see any improvements I make as new commits in the repo.
