### ISSUE TITLE
AttributeError: module 'torchvision.models.vgg' has no attribute 'cfgs'

### ISSUE THREAD

**Issue by c1a1o1** [grey-eye/talking-heads#9]
model = vgg.VGG(vgg.make_layers(vgg.cfgs['D'], batch_norm=False), num_classes=2622, **kwargs)
AttributeError: module 'torchvision.models.vgg' has no attribute 'cfgs'

**Comment by zhenzhen823** [comment]
When using torchvision < 0.3.0, such error occurs. 
But when using torchvision==0.3.0, another error occurs.
So I used torchvision 0.2.2post3, modifying 
model = vgg.VGG(vgg.make_layers(vgg.cfgs['D'], batch_norm=False), num_classes=2622, **kwargs)
into
model = vgg.VGG(vgg.make_layers(vgg.cfg['D'], batch_norm=False), num_classes=2622, **kwargs)

**Comment by MrCaracara** [comment]
Just check the sourcecode of the vgg.py file of your torchvision version and adapt the code accordingly. https://pytorch.org/docs/stable/_modules/torchvision/models/vgg.html
As you can see, in the stable release the dictionary is called `cgfs` with an s

**Comment by c1a1o1** [comment]
Thank you very much!
